{
 "title": "SSH Connections",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "SSH Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failed SSH Connections in the Last 30 Minutes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssh_failed_connection_in_the_last_30_minuts",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful SSH Connections in the last 30 Minutes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssh_successful_connection_in_the_last_30_minuts",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "ssh_successful_connection_in_the_last_30_minuts",
     "legendFormat": "__auto"
    },
    {
     "expr": "ssh_failed_connection_in_the_last_30_minuts",
     "legendFormat": "__auto"
    },
    {
     "expr": "ssh_connection_in_the_last_30_minuts",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proportions",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 7, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssh_successful_connection_in_the_last_30_minuts",
     "legendFormat": "__auto"
    },
    {
     "expr": "ssh_failed_connection_in_the_last_30_minuts",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients That Send in the past 30 Minutes a Request",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 17, "x": 7, "y": 23 },
   "targets": [
    {
     "expr": "sum by(Host) (ssh_host_connection{Request=\"Successful\"}) ",
     "legendFormat": "{{Host}} Sucess"
    },
    {
     "expr": "sum by (Host) (ssh_host_connection{Request=\"Failed\"})",
     "legendFormat": "{{Host}} Failed"
    }
   ]
  }
 ]
}